# Generated by Django 6.0.2 on 2026-02-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='last_checked',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
