# Generated by Django 5.2.11 on 2026-02-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_website_is_active_alter_website_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['website', 'checked_at'], name='app_checkre_website_cbbf9b_idx'),
        ),
    ]
