name: Deploy to Defang

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: website-monitor
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy with Defang
        uses: DefangLabs/defang-github-action@v1
        with:
          project: website-monitor-backend
          config-env-vars: |
            MYSQL_PASSWORD
            DJANGO_SECRET_KEY
            ALLOWED_HOSTS
            MYSQL_DATABASE
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}